name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build --no-restore -c release ./src
    - name: Test
      run: dotnet test --no-build --verbosity normal -c release ./src
    - name: Publish ZeroIoC.Core NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./src/ZeroIoC.Core/ZeroIoC.Core.csproj
        VERSION_FILE_PATH: ./src/Directory.Build.props
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
    - name: Publish ZeroIoC.SourceGenerator NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./src/ZeroIoC.SourceGenerator/ZeroIoC.SourceGenerator.csproj
        VERSION_FILE_PATH: ./src/Directory.Build.props
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
    - name: Publish ZeroIoC NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./src/ZeroIoC/ZeroIoC.csproj
        VERSION_FILE_PATH: ./src/Directory.Build.props
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
