name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish ZeroIoC.Core NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: /src/ZeroIoC.Core/ZeroIoC.Core.csproj
        NUGET_KEY: oy2bxqn6fyrtrbvigtda4hzubq7y5r2edhkfz63ynupxga
    - name: Publish ZeroIoC.SourceGenerator NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: /src/ZeroIoC.SourceGenerator/ZeroIoC.SourceGenerator.csproj
        NUGET_KEY: oy2bxqn6fyrtrbvigtda4hzubq7y5r2edhkfz63ynupxga
    - name: Publish ZeroIoC NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: /src/ZeroIoC/ZeroIoC.csproj
        NUGET_KEY: oy2bxqn6fyrtrbvigtda4hzubq7y5r2edhkfz63ynupxga
